app = "longalive"
primary_region = "hkg"

[build]
  image = "janjangao/sing-box-ws"

[env]
  PORT = "8888"

[[services]]
  internal_port = 8888
  protocol = "tcp"
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  internal_port = 8443
  protocol = "udp"
  [[services.ports]]
    port = 8443