app = "longalive"
primary_region = "hkg"

[build]
  image = "janjangao/sing-box-ws"
[build.args]
  HTTPS_REDIRECT="true"

[[services]]
  internal_port = 80
  protocol = "tcp"
  [[services.ports]]
    port = 80
    handlers = ["http"]

[[services]]
  internal_port = 443
  protocol = "tcp"
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  internal_port = 8443
  protocol = "udp"
  [[services.ports]]
    port = 8443